name: Build and Deploy to GKE DEV

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: cloudside-academy
  GKE_CLUSTER: sudhakar-test
  GKE_ZONE: us-central1-c
  REPO_NAME: sudhakar-test
  IMAGE: github-action
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: Installing packages
        run: |-
          gcloud components install gke-gcloud-auth-plugin 
        
      - name: Get GKE Credentials
        env :
          USE_GCLOUD_AUTH_PLUGIN: true
        run: |-
          gcloud container clusters get-credentials sudhakar-test --zone us-central1-c --project cloudside-academy
          
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Deploy Image to GKE cluster
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/nginx

      
      
