name: Build and Deploy to GKE DEV

on:
  push:
    branches:
      - coupon-service-dev

env:
  PROJECT_ID: cloudside-academy
  GKE_CLUSTER: sudhakar-test
  GKE_ZONE: us-central1-c
  REPO_NAME: sudhakar-test
  IMAGE: manual approval
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      
      
